///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginSteps recording.
    /// </summary>
    [TestModule("d27329f2-d2f3-4052-8b77-aa3a6b458d92", ModuleType.Recording, 1)]
    public partial class LoginSteps : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest_2Repository repository.
        /// </summary>
        public static MyTest_2Repository repo = MyTest_2Repository.Instance;

        static LoginSteps instance = new LoginSteps();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginSteps()
        {
            Username = "Test";
            Password = "Test";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginSteps Instance
        {
            get { return instance; }
        }

#region Variables

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("a73da126-4f7a-4836-8ce5-b5886d0af47d")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("2029f752-2b31-41fa-b700-9d7a054c9f97")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsername' at 39;25.", repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsernameInfo, new RecordItemIndex(0));
            repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsername.Click("39;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsername'.", repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsernameInfo, new RecordItemIndex(1));
            repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtUsername.PressKeys(Username);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.LoginPage.TxtPassword' at 144;36.", repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtPasswordInfo, new RecordItemIndex(2));
            repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtPassword.Click("144;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'CURAHealthcareServiceGoogleChrome.LoginPage.TxtPassword'.", repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtPasswordInfo, new RecordItemIndex(3));
            repo.CURAHealthcareServiceGoogleChrome.LoginPage.TxtPassword.PressKeys(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.LoginPage.BtnLogin' at 38;22.", repo.CURAHealthcareServiceGoogleChrome.LoginPage.BtnLoginInfo, new RecordItemIndex(4));
            repo.CURAHealthcareServiceGoogleChrome.LoginPage.BtnLogin.Click("38;22");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
