///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MakeAppointmentBookedScenarioSteps recording.
    /// </summary>
    [TestModule("c3f47109-436c-4f91-a919-2413ee9b03d5", ModuleType.Recording, 1)]
    public partial class MakeAppointmentBookedScenarioSteps : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest_2Repository repository.
        /// </summary>
        public static MyTest_2Repository repo = MyTest_2Repository.Instance;

        static MakeAppointmentBookedScenarioSteps instance = new MakeAppointmentBookedScenarioSteps();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MakeAppointmentBookedScenarioSteps()
        {
            HealthcareProgramType = "Medicare";
            FacilityType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MakeAppointmentBookedScenarioSteps Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable HealthcareProgramType.
        /// </summary>
        [TestVariable("9a2eda43-fb26-4d17-89de-29788f80cf3e")]
        public string HealthcareProgramType
        {
            get { return repo.HealthcareProgramType; }
            set { repo.HealthcareProgramType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable FacilityType.
        /// </summary>
        [TestVariable("f2221938-d4c6-4ee2-9e13-a4c87f62487a")]
        public string FacilityType
        {
            get { return repo.FacilityType; }
            set { repo.FacilityType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceAnd6MorePages.ComboFacility' at 148;24.", repo.CURAHealthcareServiceAnd6MorePages.ComboFacilityInfo, new RecordItemIndex(0));
            //repo.CURAHealthcareServiceAnd6MorePages.ComboFacility.Click("148;24");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FacilityType' with focus on 'CURAHealthcareServiceAnd6MorePages.ComboFacility'.", repo.CURAHealthcareServiceAnd6MorePages.ComboFacilityInfo, new RecordItemIndex(1));
            repo.CURAHealthcareServiceAnd6MorePages.ComboFacility.PressKeys(FacilityType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yourtext' with focus on 'CURAHealthcareServiceAnd6MorePages.ComboFacility'.", repo.CURAHealthcareServiceAnd6MorePages.ComboFacilityInfo, new RecordItemIndex(2));
            repo.CURAHealthcareServiceAnd6MorePages.ComboFacility.PressKeys("yourtext");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Seoul CURA Healthcare Center' on item 'CURAHealthcareServiceAnd6MorePages.ComboFacility'.", repo.CURAHealthcareServiceAnd6MorePages.ComboFacilityInfo, new RecordItemIndex(3));
            //repo.CURAHealthcareServiceAnd6MorePages.ComboFacility.Element.SetAttributeValue("Text", "Seoul CURA Healthcare Center");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmission' at 6;6.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmissionInfo, new RecordItemIndex(4));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmission.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'True' on item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmission'.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmissionInfo, new RecordItemIndex(5));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.ChkboxHospotalReadmission.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.RadioProgramMedicare' at 9;7.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.RadioProgramMedicareInfo, new RecordItemIndex(6));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.RadioProgramMedicare.Click("9;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDate' at 33;30.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDateInfo, new RecordItemIndex(7));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDate.Click("33;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10/12/2028' with focus on 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDate'.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDateInfo, new RecordItemIndex(8));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtVisitDate.PressKeys("10/12/2028");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtComment' at 55;44.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtCommentInfo, new RecordItemIndex(9));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtComment.Click("55;44");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtComment'.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtCommentInfo, new RecordItemIndex(10));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.TxtComment.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.BtnBookAppointment' at 98;19.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.BtnBookAppointmentInfo, new RecordItemIndex(11));
            repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.BtnBookAppointment.Click("98;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Appointment Confirmation') on item 'CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.AppointmentConfirmation'.", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.AppointmentConfirmationInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.AppointmentConfirmationInfo, "Text", "Appointment Confirmation");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Summary' at 0;181.", repo.CURAHealthcareServiceGoogleChrome.SummaryInfo, new RecordItemIndex(13));
            repo.CURAHealthcareServiceGoogleChrome.Summary.Click("0;181");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "Appointment Confirmation", repo.CURAHealthcareServiceGoogleChrome.MakeAppointmentConfirmationPage.AppointmentConfirmation, false, new RecordItemIndex(14));
            
            Report.Screenshot(ReportLevel.Info, "User", "Appointment Confirmation Details", repo.CURAHealthcareServiceGoogleChrome.Summary, false, new RecordItemIndex(15));
            
            ValidateCheckboxAction();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
