///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest_2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("006cdd6f-eb46-4d77-8a2e-326559a48c5f")]
    public partial class MyTest_2Repository : RepoGenBaseFolder
    {
        static MyTest_2Repository instance = new MyTest_2Repository();
        MyTest_2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest_2RepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder _curahealthcareservicegooglechrome;
        MyTest_2RepositoryFolders.HomePageFolder _homepage;
        MyTest_2RepositoryFolders.CURAHealthcareServiceAnd6MorePagesAppFolder _curahealthcareserviceand6morepages;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest_2Repository element repository.
        /// </summary>
        [RepositoryFolder("006cdd6f-eb46-4d77-8a2e-326559a48c5f")]
        public static MyTest_2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest_2Repository() 
            : base("MyTest_2Repository", "/", null, 0, false, "006cdd6f-eb46-4d77-8a2e-326559a48c5f", ".\\RepositoryImages\\MyTest_2Repository006cdd6f.rximgres")
        {
            _applicationundertest = new MyTest_2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _curahealthcareservicegooglechrome = new MyTest_2RepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder(this);
            _homepage = new MyTest_2RepositoryFolders.HomePageFolder(this);
            _curahealthcareserviceand6morepages = new MyTest_2RepositoryFolders.CURAHealthcareServiceAnd6MorePagesAppFolder(this);
        }

#region Variables

        string _HealthcareProgramType = "Medicare";

        /// <summary>
        /// Gets or sets the value of variable HealthcareProgramType.
        /// </summary>
        [TestVariable("26a1ef91-7177-43b6-8f83-7641ddd96be4")]
        public string HealthcareProgramType
        {
            get { return _HealthcareProgramType; }
            set { _HealthcareProgramType = value; }
        }

        string _FacilityType = "";

        /// <summary>
        /// Gets or sets the value of variable FacilityType.
        /// </summary>
        [TestVariable("f2221938-d4c6-4ee2-9e13-a4c87f62487a")]
        public string FacilityType
        {
            get { return _FacilityType; }
            set { _FacilityType = value; }
        }

        string _F = "";

        /// <summary>
        /// Gets or sets the value of variable F.
        /// </summary>
        [TestVariable("d181b0cb-0173-4d65-9c5b-aeff6b1aa382")]
        public string F
        {
            get { return _F; }
            set { _F = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("006cdd6f-eb46-4d77-8a2e-326559a48c5f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4530af48-7680-41af-bcb6-359549217f16")]
        public virtual MyTest_2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The CURAHealthcareServiceGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("d8c418c4-10eb-4206-8cb7-50aa3b456dfe")]
        public virtual MyTest_2RepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder CURAHealthcareServiceGoogleChrome
        {
            get { return _curahealthcareservicegooglechrome; }
        }

        /// <summary>
        /// The HomePage folder.
        /// </summary>
        [RepositoryFolder("62e63402-67e1-4812-9805-d176bb381683")]
        public virtual MyTest_2RepositoryFolders.HomePageFolder HomePage
        {
            get { return _homepage; }
        }

        /// <summary>
        /// The CURAHealthcareServiceAnd6MorePages folder.
        /// </summary>
        [RepositoryFolder("466aad3b-a9a8-4b31-b230-b81b2d6280fa")]
        public virtual MyTest_2RepositoryFolders.CURAHealthcareServiceAnd6MorePagesAppFolder CURAHealthcareServiceAnd6MorePages
        {
            get { return _curahealthcareserviceand6morepages; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest_2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4530af48-7680-41af-bcb6-359549217f16")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@title>'CURA Healthcare Service -']//text[@automationid='view_1012']", parentFolder, 30000, null, false, "4530af48-7680-41af-bcb6-359549217f16", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4530af48-7680-41af-bcb6-359549217f16")]
            public virtual Ranorex.Text Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4530af48-7680-41af-bcb6-359549217f16")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CURAHealthcareServiceGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8c418c4-10eb-4206-8cb7-50aa3b456dfe")]
        public partial class CURAHealthcareServiceGoogleChromeAppFolder : RepoGenBaseFolder
        {
            MyTest_2RepositoryFolders.LoginPageFolder _loginpage;
            MyTest_2RepositoryFolders.LogoutPageFolder _logoutpage;
            MyTest_2RepositoryFolders.ErrorMessageTextValidationPageFolder _errormessagetextvalidationpage;
            MyTest_2RepositoryFolders.MakeAppointmentTextValidationsPageFolder _makeappointmenttextvalidationspage;
            MyTest_2RepositoryFolders.MakeAppointmentConfirmationPageFolder _makeappointmentconfirmationpage;
            RepoItemInfo _summaryInfo;

            /// <summary>
            /// Creates a new CURAHealthcareServiceGoogleChrome  folder.
            /// </summary>
            public CURAHealthcareServiceGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CURAHealthcareServiceGoogleChrome", "/form[@title>'CURA Healthcare Service -']", parentFolder, 30000, null, true, "d8c418c4-10eb-4206-8cb7-50aa3b456dfe", "")
            {
                _loginpage = new MyTest_2RepositoryFolders.LoginPageFolder(this);
                _logoutpage = new MyTest_2RepositoryFolders.LogoutPageFolder(this);
                _errormessagetextvalidationpage = new MyTest_2RepositoryFolders.ErrorMessageTextValidationPageFolder(this);
                _makeappointmenttextvalidationspage = new MyTest_2RepositoryFolders.MakeAppointmentTextValidationsPageFolder(this);
                _makeappointmentconfirmationpage = new MyTest_2RepositoryFolders.MakeAppointmentConfirmationPageFolder(this);
                _summaryInfo = new RepoItemInfo(this, "Summary", ".//container[@automationid='summary']", ".//container[@automationid='summary']", 30000, null, "5c7eed60-bb13-4c8f-85d6-4e0156bfc767");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8c418c4-10eb-4206-8cb7-50aa3b456dfe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8c418c4-10eb-4206-8cb7-50aa3b456dfe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Summary item.
            /// </summary>
            [RepositoryItem("5c7eed60-bb13-4c8f-85d6-4e0156bfc767")]
            public virtual Ranorex.Container Summary
            {
                get
                {
                    return _summaryInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Summary item info.
            /// </summary>
            [RepositoryItemInfo("5c7eed60-bb13-4c8f-85d6-4e0156bfc767")]
            public virtual RepoItemInfo SummaryInfo
            {
                get
                {
                    return _summaryInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("662a70ad-a0f9-40a0-a8eb-81fae127e9aa")]
            public virtual MyTest_2RepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The LogoutPage folder.
            /// </summary>
            [RepositoryFolder("dc37dadc-94bb-432b-bfd2-0eb030d8cc24")]
            public virtual MyTest_2RepositoryFolders.LogoutPageFolder LogoutPage
            {
                get { return _logoutpage; }
            }

            /// <summary>
            /// The ErrorMessageTextValidationPage folder.
            /// </summary>
            [RepositoryFolder("2bc208fa-e57f-42e7-ae97-68b3e017f485")]
            public virtual MyTest_2RepositoryFolders.ErrorMessageTextValidationPageFolder ErrorMessageTextValidationPage
            {
                get { return _errormessagetextvalidationpage; }
            }

            /// <summary>
            /// The MakeAppointmentTextValidationsPage folder.
            /// </summary>
            [RepositoryFolder("79149d06-8f28-4119-be40-4f5241193c46")]
            public virtual MyTest_2RepositoryFolders.MakeAppointmentTextValidationsPageFolder MakeAppointmentTextValidationsPage
            {
                get { return _makeappointmenttextvalidationspage; }
            }

            /// <summary>
            /// The MakeAppointmentConfirmationPage folder.
            /// </summary>
            [RepositoryFolder("dafbda24-2fbd-43b8-bd8b-3c6222f06cd8")]
            public virtual MyTest_2RepositoryFolders.MakeAppointmentConfirmationPageFolder MakeAppointmentConfirmationPage
            {
                get { return _makeappointmentconfirmationpage; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("662a70ad-a0f9-40a0-a8eb-81fae127e9aa")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 0, null, false, "662a70ad-a0f9-40a0-a8eb-81fae127e9aa", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUsername", ".//text[@automationid='txt-username']", ".//text[@automationid='txt-username']", 30000, null, "fb18c692-9945-4383-9253-3880233496f7");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//text[@automationid='txt-password']", ".//text[@automationid='txt-password']", 30000, null, "ee1efa85-fd48-4cc2-96e3-2dded51dbca7");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//button[@automationid='btn-login']", ".//button[@automationid='btn-login']", 30000, null, "d6e3244e-3865-4cc0-8dec-46772d385e47");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("662a70ad-a0f9-40a0-a8eb-81fae127e9aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUsername item.
            /// </summary>
            [RepositoryItem("fb18c692-9945-4383-9253-3880233496f7")]
            public virtual Ranorex.Text TxtUsername
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUsername item info.
            /// </summary>
            [RepositoryItemInfo("fb18c692-9945-4383-9253-3880233496f7")]
            public virtual RepoItemInfo TxtUsernameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("ee1efa85-fd48-4cc2-96e3-2dded51dbca7")]
            public virtual Ranorex.Text TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("ee1efa85-fd48-4cc2-96e3-2dded51dbca7")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("d6e3244e-3865-4cc0-8dec-46772d385e47")]
            public virtual Ranorex.Button BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("d6e3244e-3865-4cc0-8dec-46772d385e47")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The LogoutPageFolder folder.
        /// </summary>
        [RepositoryFolder("dc37dadc-94bb-432b-bfd2-0eb030d8cc24")]
        public partial class LogoutPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;
            RepoItemInfo _menutoggleInfo;

            /// <summary>
            /// Creates a new LogoutPage  folder.
            /// </summary>
            public LogoutPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LogoutPage", "", parentFolder, 0, null, false, "dc37dadc-94bb-432b-bfd2-0eb030d8cc24", "")
            {
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//text[@name='Logout']", ".//text[@name='Logout']", 30000, null, "22eaa7f9-15c8-4d6f-91c2-9b90b8640d70");
                _menutoggleInfo = new RepoItemInfo(this, "MenuToggle", ".//link[@automationid='menu-toggle']", ".//link[@automationid='menu-toggle']", 30000, null, "8194d1fc-a005-425c-89fe-85f39ab1603a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc37dadc-94bb-432b-bfd2-0eb030d8cc24")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("22eaa7f9-15c8-4d6f-91c2-9b90b8640d70")]
            public virtual Ranorex.Text Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("22eaa7f9-15c8-4d6f-91c2-9b90b8640d70")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The MenuToggle item.
            /// </summary>
            [RepositoryItem("8194d1fc-a005-425c-89fe-85f39ab1603a")]
            public virtual Ranorex.Link MenuToggle
            {
                get
                {
                    return _menutoggleInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The MenuToggle item info.
            /// </summary>
            [RepositoryItemInfo("8194d1fc-a005-425c-89fe-85f39ab1603a")]
            public virtual RepoItemInfo MenuToggleInfo
            {
                get
                {
                    return _menutoggleInfo;
                }
            }
        }

        /// <summary>
        /// The ErrorMessageTextValidationPageFolder folder.
        /// </summary>
        [RepositoryFolder("2bc208fa-e57f-42e7-ae97-68b3e017f485")]
        public partial class ErrorMessageTextValidationPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginfailedpleaseensuretheusernameInfo;

            /// <summary>
            /// Creates a new ErrorMessageTextValidationPage  folder.
            /// </summary>
            public ErrorMessageTextValidationPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ErrorMessageTextValidationPage", "", parentFolder, 0, null, false, "2bc208fa-e57f-42e7-ae97-68b3e017f485", "")
            {
                _loginfailedpleaseensuretheusernameInfo = new RepoItemInfo(this, "LoginFailedPleaseEnsureTheUsername", ".//text[@name>'Login failed! Please ensure']", ".//text[@name>'Login failed! Please ensure']", 30000, null, "ece1f4ab-cb85-47b8-a194-6dff4bda05a8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2bc208fa-e57f-42e7-ae97-68b3e017f485")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginFailedPleaseEnsureTheUsername item.
            /// </summary>
            [RepositoryItem("ece1f4ab-cb85-47b8-a194-6dff4bda05a8")]
            public virtual Ranorex.Text LoginFailedPleaseEnsureTheUsername
            {
                get
                {
                    return _loginfailedpleaseensuretheusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginFailedPleaseEnsureTheUsername item info.
            /// </summary>
            [RepositoryItemInfo("ece1f4ab-cb85-47b8-a194-6dff4bda05a8")]
            public virtual RepoItemInfo LoginFailedPleaseEnsureTheUsernameInfo
            {
                get
                {
                    return _loginfailedpleaseensuretheusernameInfo;
                }
            }
        }

        /// <summary>
        /// The MakeAppointmentTextValidationsPageFolder folder.
        /// </summary>
        [RepositoryFolder("79149d06-8f28-4119-be40-4f5241193c46")]
        public partial class MakeAppointmentTextValidationsPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _makeappointmentheadertextInfo;
            RepoItemInfo _makeappointmenttitletextInfo;

            /// <summary>
            /// Creates a new MakeAppointmentTextValidationsPage  folder.
            /// </summary>
            public MakeAppointmentTextValidationsPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MakeAppointmentTextValidationsPage", "", parentFolder, 0, null, false, "79149d06-8f28-4119-be40-4f5241193c46", "")
            {
                _makeappointmentheadertextInfo = new RepoItemInfo(this, "MakeAppointmentHeaderText", "element//text[@orientation='None' and @caption='Make Appointment' and @iscontentelement='True']/text[@name='Make Appointment']", ".//text[@orientation='None' and @caption='Make Appointment' and @iscontentelement='True']/text[@name='Make Appointment']", 30000, null, "f1023048-104f-4fb8-89ee-dcaa7f8874c3");
                _makeappointmenttitletextInfo = new RepoItemInfo(this, "MakeAppointmentTitleText", ".//tabpage[@automationid='view_20' and @name='CURA Healthcare Service']", "", 30000, null, "913d7f0f-3b4a-4384-9063-adf05b0ec26b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("79149d06-8f28-4119-be40-4f5241193c46")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MakeAppointmentHeaderText item.
            /// </summary>
            [RepositoryItem("f1023048-104f-4fb8-89ee-dcaa7f8874c3")]
            public virtual Ranorex.Text MakeAppointmentHeaderText
            {
                get
                {
                    return _makeappointmentheadertextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MakeAppointmentHeaderText item info.
            /// </summary>
            [RepositoryItemInfo("f1023048-104f-4fb8-89ee-dcaa7f8874c3")]
            public virtual RepoItemInfo MakeAppointmentHeaderTextInfo
            {
                get
                {
                    return _makeappointmentheadertextInfo;
                }
            }

            /// <summary>
            /// The MakeAppointmentTitleText item.
            /// </summary>
            [RepositoryItem("913d7f0f-3b4a-4384-9063-adf05b0ec26b")]
            public virtual Ranorex.TabPage MakeAppointmentTitleText
            {
                get
                {
                    return _makeappointmenttitletextInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MakeAppointmentTitleText item info.
            /// </summary>
            [RepositoryItemInfo("913d7f0f-3b4a-4384-9063-adf05b0ec26b")]
            public virtual RepoItemInfo MakeAppointmentTitleTextInfo
            {
                get
                {
                    return _makeappointmenttitletextInfo;
                }
            }
        }

        /// <summary>
        /// The MakeAppointmentConfirmationPageFolder folder.
        /// </summary>
        [RepositoryFolder("dafbda24-2fbd-43b8-bd8b-3c6222f06cd8")]
        public partial class MakeAppointmentConfirmationPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkboxhospotalreadmissionInfo;
            RepoItemInfo _radioprogrammedicareInfo;
            RepoItemInfo _txtvisitdateInfo;
            RepoItemInfo _txtcommentInfo;
            RepoItemInfo _btnbookappointmentInfo;
            RepoItemInfo _appointmentconfirmationInfo;

            /// <summary>
            /// Creates a new MakeAppointmentConfirmationPage  folder.
            /// </summary>
            public MakeAppointmentConfirmationPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MakeAppointmentConfirmationPage", "", parentFolder, 0, null, false, "dafbda24-2fbd-43b8-bd8b-3c6222f06cd8", "")
            {
                _chkboxhospotalreadmissionInfo = new RepoItemInfo(this, "ChkboxHospotalReadmission", ".//checkbox[@automationid='chk_hospotal_readmission']", ".//checkbox[@automationid='chk_hospotal_readmission']", 30000, null, "830e0992-11ca-4906-a8f6-de2d80683082");
                _radioprogrammedicareInfo = new RepoItemInfo(this, "RadioProgramMedicare", ".//radiobutton[@text=$HealthcareProgramType]", "", 30000, null, "1300d7f2-ed7f-4113-a790-5884a23c65bf");
                _txtvisitdateInfo = new RepoItemInfo(this, "TxtVisitDate", ".//text[@automationid='txt_visit_date']", ".//text[@automationid='txt_visit_date']", 30000, null, "062261b7-a163-4a3b-a79c-547b4a6fc84d");
                _txtcommentInfo = new RepoItemInfo(this, "TxtComment", ".//text[@automationid='txt_comment']", ".//text[@automationid='txt_comment']", 30000, null, "6c654bc5-1ee1-4325-8176-2b1ebdaa78c7");
                _btnbookappointmentInfo = new RepoItemInfo(this, "BtnBookAppointment", ".//button[@automationid='btn-book-appointment']", ".//button[@automationid='btn-book-appointment']", 30000, null, "c561fbcc-5065-446d-9f20-90def1b23219");
                _appointmentconfirmationInfo = new RepoItemInfo(this, "AppointmentConfirmation", ".//text[@orientation='None' and @caption='Appointment Confirmation' and @iscontentelement='False']", ".//text[@orientation='None' and @caption='Appointment Confirmation' and @iscontentelement='False']", 30000, null, "7550999f-3159-4c32-a102-6f9a88b7a40a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dafbda24-2fbd-43b8-bd8b-3c6222f06cd8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkboxHospotalReadmission item.
            /// </summary>
            [RepositoryItem("830e0992-11ca-4906-a8f6-de2d80683082")]
            public virtual Ranorex.CheckBox ChkboxHospotalReadmission
            {
                get
                {
                    return _chkboxhospotalreadmissionInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkboxHospotalReadmission item info.
            /// </summary>
            [RepositoryItemInfo("830e0992-11ca-4906-a8f6-de2d80683082")]
            public virtual RepoItemInfo ChkboxHospotalReadmissionInfo
            {
                get
                {
                    return _chkboxhospotalreadmissionInfo;
                }
            }

            /// <summary>
            /// The RadioProgramMedicare item.
            /// </summary>
            [RepositoryItem("1300d7f2-ed7f-4113-a790-5884a23c65bf")]
            public virtual Ranorex.RadioButton RadioProgramMedicare
            {
                get
                {
                    return _radioprogrammedicareInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioProgramMedicare item info.
            /// </summary>
            [RepositoryItemInfo("1300d7f2-ed7f-4113-a790-5884a23c65bf")]
            public virtual RepoItemInfo RadioProgramMedicareInfo
            {
                get
                {
                    return _radioprogrammedicareInfo;
                }
            }

            /// <summary>
            /// The TxtVisitDate item.
            /// </summary>
            [RepositoryItem("062261b7-a163-4a3b-a79c-547b4a6fc84d")]
            public virtual Ranorex.Text TxtVisitDate
            {
                get
                {
                    return _txtvisitdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtVisitDate item info.
            /// </summary>
            [RepositoryItemInfo("062261b7-a163-4a3b-a79c-547b4a6fc84d")]
            public virtual RepoItemInfo TxtVisitDateInfo
            {
                get
                {
                    return _txtvisitdateInfo;
                }
            }

            /// <summary>
            /// The TxtComment item.
            /// </summary>
            [RepositoryItem("6c654bc5-1ee1-4325-8176-2b1ebdaa78c7")]
            public virtual Ranorex.Text TxtComment
            {
                get
                {
                    return _txtcommentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtComment item info.
            /// </summary>
            [RepositoryItemInfo("6c654bc5-1ee1-4325-8176-2b1ebdaa78c7")]
            public virtual RepoItemInfo TxtCommentInfo
            {
                get
                {
                    return _txtcommentInfo;
                }
            }

            /// <summary>
            /// The BtnBookAppointment item.
            /// </summary>
            [RepositoryItem("c561fbcc-5065-446d-9f20-90def1b23219")]
            public virtual Ranorex.Button BtnBookAppointment
            {
                get
                {
                    return _btnbookappointmentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnBookAppointment item info.
            /// </summary>
            [RepositoryItemInfo("c561fbcc-5065-446d-9f20-90def1b23219")]
            public virtual RepoItemInfo BtnBookAppointmentInfo
            {
                get
                {
                    return _btnbookappointmentInfo;
                }
            }

            /// <summary>
            /// The AppointmentConfirmation item.
            /// </summary>
            [RepositoryItem("7550999f-3159-4c32-a102-6f9a88b7a40a")]
            public virtual Ranorex.Text AppointmentConfirmation
            {
                get
                {
                    return _appointmentconfirmationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AppointmentConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("7550999f-3159-4c32-a102-6f9a88b7a40a")]
            public virtual RepoItemInfo AppointmentConfirmationInfo
            {
                get
                {
                    return _appointmentconfirmationInfo;
                }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("62e63402-67e1-4812-9805-d176bb381683")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _makeappointmentbuttonInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "62e63402-67e1-4812-9805-d176bb381683", "")
            {
                _makeappointmentbuttonInfo = new RepoItemInfo(this, "MakeAppointmentButton", "/form[@title>'CURA Healthcare Service -']//text[@name='Make Appointment']", "/form[@title>'CURA Healthcare Service -']//text[@name='Make Appointment']", 30000, null, "c85e67ac-14a5-4122-8424-1ed8f6bd64c7");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("62e63402-67e1-4812-9805-d176bb381683")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MakeAppointmentButton item.
            /// </summary>
            [RepositoryItem("c85e67ac-14a5-4122-8424-1ed8f6bd64c7")]
            public virtual Ranorex.Text MakeAppointmentButton
            {
                get
                {
                    return _makeappointmentbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MakeAppointmentButton item info.
            /// </summary>
            [RepositoryItemInfo("c85e67ac-14a5-4122-8424-1ed8f6bd64c7")]
            public virtual RepoItemInfo MakeAppointmentButtonInfo
            {
                get
                {
                    return _makeappointmentbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CURAHealthcareServiceAnd6MorePagesAppFolder folder.
        /// </summary>
        [RepositoryFolder("466aad3b-a9a8-4b31-b230-b81b2d6280fa")]
        public partial class CURAHealthcareServiceAnd6MorePagesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _combofacilityInfo;

            /// <summary>
            /// Creates a new CURAHealthcareServiceAnd6MorePages  folder.
            /// </summary>
            public CURAHealthcareServiceAnd6MorePagesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CURAHealthcareServiceAnd6MorePages", "/form[@title>'CURA Healthcare Service and']", parentFolder, 30000, null, true, "466aad3b-a9a8-4b31-b230-b81b2d6280fa", "")
            {
                _combofacilityInfo = new RepoItemInfo(this, "ComboFacility", ".//combobox[@automationid='combo_facility']", "", 30000, null, "54a19f69-909c-4306-baac-ee8fa64416ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("466aad3b-a9a8-4b31-b230-b81b2d6280fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("466aad3b-a9a8-4b31-b230-b81b2d6280fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboFacility item.
            /// </summary>
            [RepositoryItem("54a19f69-909c-4306-baac-ee8fa64416ff")]
            public virtual Ranorex.ComboBox ComboFacility
            {
                get
                {
                    return _combofacilityInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboFacility item info.
            /// </summary>
            [RepositoryItemInfo("54a19f69-909c-4306-baac-ee8fa64416ff")]
            public virtual RepoItemInfo ComboFacilityInfo
            {
                get
                {
                    return _combofacilityInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
